version: "3.9"

services:  

  mysql:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    image: mysql/mysql-server:8.0.23
    container_name: mysql
    restart: always 
    tty: true
    volumes:
      - ./mysql/data:/var/lib/mysql
    networks:
      - node-network
    ports:
      - "3306:3306"

  node: 
    build:
      context: ./nodejs
      dockerfile: Dockerfile.prod
    image: csmaniotto/node_fullcycle
    container_name: node
    networks:
      - node-network
    ports:
      - "3000:3000"
    volumes:
      - ./nodejs:/usr/src/app
    tty: true
    working_dir: /usr/src/app
    entrypoint: dockerize -wait tcp://mysql:3306 -timeout 20s /usr/local/bin/node index.js
    depends_on:
      - mysql

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile_node.prod
    image: csmaniotto/nginx_fullcyle
    container_name: nginx
    networks:
      - node-network
    ports:
      - 8080:80
    tty: true
    depends_on:
     - node

networks:
  node-network:
    driver: bridge
