version: "3.9"

services:  
  db:
    image: mysql/mysql-server:8.0.23
    command: --default-authentication-plugin=mysql_native_password
    container_name: db
    restart: always 
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_HOST=%
      - TZ=America/SaoPaulo
    networks:
      - node-network
    ports:
      - "3306:3306"

  app: 
    build:
      context: ./nodejs
      dockerfile: Dockerfile.prod
    image: csmaniotto/node_fullcycle
    container_name: node_mysql
    networks:
      - node-network
    ports:
      - "3000:3000"
    volumes:
      - ./nodejs:/usr/src/app
    tty: true
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s node index.js &
    depends_on:
      - db

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile_node.prod
    image: csmaniotto/nginx_fullcyle
    container_name: nginx_node
    networks:
      - node-network
    ports:
      - 8080:80
    tty: true
    depends_on:
      - app


networks:
  node-network:
    driver: bridge
